version: '2'

services:
  redis:
    image: redis:3

  datadromm:
    build: .
    ports:
      - 3000
    links:
      - redis
    environment:
      REDISURL: redis://redis:6379
      PORT: 3000

  lb:
    image: dockercloud/haproxy
    links:
      - datadromm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
